ControleGestaoFtth/Models/EstadoCampo.cs
using System.ComponentModel.DataAnnotations;

namespace ControleGestaoFtth.Models
{
    public class EstadoCampo
    {
        [Key]
        public int Id { get; set; }
        public string Nome { get; set; } = null!;
    }
}

ControleGestaoFtth/Models/EstadoCampos.cs
using System.ComponentModel.DataAnnotations;

namespace ControleGestaoFtth.Models
{
    public class EstadoCampos
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string? Nome { get; set; }
    }
}

ControleGestaoFtth/Controllers/EstadoCampoController.cs
using ControleGestaoFtth.Models;
using ControleGestaoFtth.Repository.Interface;
using Microsoft.AspNetCore.Mvc;

namespace ControleGestaoFtth.Controllers
{
    public class EstadoCampoController : Controller
    {
        private readonly IEstadoCampoRepository _estadoCampoRepository;

        public EstadoCampoController(IEstadoCampoRepository estadoCampoRepository)
        {
            _estadoCampoRepository = estadoCampoRepository;
        }
        public IActionResult Index()
        {
            ViewData["selectCampo"] = _estadoCampoRepository.Campo();
            return View();
        }
        public IActionResult Inserir()
        {
            return View();
        }
        public IActionResult Editar(int id)
        {
            EstadoCampo estadoCampo = _estadoCampoRepository.CarregarId(id);

            return View(estadoCampo);
        }
        public IActionResult Confirmacao(int id)
        {
            EstadoCampo estadoCampo = _estadoCampoRepository.CarregarId(id);

            return View(estadoCampo);
        }

        [HttpPost]
        public IActionResult Inserir(EstadoCampo estadoCampo)
        {
            try
            {
                if (_estadoCampoRepository.EstadoCampoExiste(estadoCampo.Nome))
                {
                    TempData["Falha"] = $"Estado Campo {estadoCampo.Nome} já existe.";

                    return View(estadoCampo);
                }
                else
                {
                    _estadoCampoRepository.Cadastrar(estadoCampo);
                    TempData["Sucesso"] = "Inserido com sucesso.";
                    return RedirectToAction("Inserir");
                }
            }
            catch (Exception error)
            {
                TempData["Falha"] = $"Erro ao inserir - {error}.";
                return View(estadoCampo);
            }
        }
        [HttpPost]
        public IActionResult Editar(EstadoCampo estadoCampo)
        {
            try
            {
                _estadoCampoRepository.Atualizar(estadoCampo);
                TempData["Sucesso"] = "Editado com sucesso.";
                return RedirectToAction("Editar", new { id = estadoCampo.Id });
            }
            catch (Exception error)
            {
                TempData["Falha"] = $"Erro ao editar - {error.Message}.";

                return View(estadoCampo);
            }
        }

        [HttpGet]
        public IActionResult Apagar(int id)
        {
            try
            {
                if (!_estadoCampoRepository.UniqueFk().Any(p => p.EstadoCamposId.Equals(id)))
                {
                    _estadoCampoRepository.Deletar(id);
                    TempData["Sucesso"] = $"Excluído com sucesso.";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Falha"] = $"Estado Campo N°{id} contém registros relacionais e não pode ser excluída.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception error)
            {
                TempData["Falha"] = $"Erro ao excluir - {error.Message}.";
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public IActionResult Detalhe(int id)
        {
            try
            {
                EstadoCampo estadoCampo = _estadoCampoRepository.CarregarId(id);

                return View(estadoCampo);
            }
            catch (Exception error)
            {
                TempData["Falha"] = $"Erro - {error.Message}.";
                return RedirectToAction("Index");
            }

        }

        [HttpGet]
        public IActionResult Listar(int? pagina, string nome)
        {
            try
            {
                IEnumerable<EstadoCampo> listar = _estadoCampoRepository.Listar(pagina, nome);

                return PartialView(listar);
            }
            catch (Exception error)
            {
                TempData["Falha"] = $"Erro - {error.Message}.";
                return PartialView();
            }


        }
    }
}

ControleGestaoFtth/Views/EstadoCampo/Confirmacao.cshtml
@model EstadoCampo
@{
    ViewData["Title"] = "Confirmação";
}
<div class="d-flex flex-row justify-content-center">
    <div class="modal-content">
        <div class="modal-header bg-primary p-2 position-relative">
            <i style="font-size:1.5rem;" class="fa fa-exclamation-circle position-absolute start-0 ms-2 text-white aria-hidden=" true""></i>
            <a style="font-size:0.9rem; font-weight: 600;" class="text-white text-decoration-none">
                -- ATENÇÃO --
            </a>
        </div>
        <div class="modal-body">
            <a id="AvisoConfirmacao">O registro N°@Model.Id referente a "@Model.Nome" será excluído permanentemente. <br /><br /> Deseja realmente excluir?   </a>
            <div class="modal-footer mt-4">
                <button onclick="location.href='@Url.Action("Apagar", "EstadoCampo", new {id = Model.Id})'" class="btn btn-primary mt-2">Confirmar</button>
                <button onclick="location.href='@Url.Action("Index", "EstadoCampo")'" class="btn btn-secondary mt-2 cancelar">Cancelar</button>
            </div>
        </div>
    </div>
</div>

ControleGestaoFtth/Views/EstadoCampo/Detalhe.cshtml
@model EstadoCampo

<div id="displayDetalheFtth">
    <!-- Condição Nula do Modal -->
    @if (Model != null)
    {
        <table id="ftthDetalhe">
            <tr>
                <td colspan="2">Estado Campo: <a>@Model.Nome</a></td>
            </tr>
        </table>

        <div class="modal-footer mt-4">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
            <a role="button" id="btnRoles" asp-controller="EstadoCampo" asp-action="Editar" asp-route-id="@Model.Id" class="btn btn-primary">Editar</a>
            <a role="button" id="btnRoles" asp-controller="EstadoCampo" asp-action="Confirmacao" asp-route-id="@Model.Id" class="btn btn-danger">Excluir</a>
        </div>
    }
    <!-- End condição -->
    </div>

ControleGestaoFtth/Views/EstadoCampo/Editar.cshtml
@model EstadoCampo

<div class="d-flex flex-row justify-content-center">
    <div class="d-flex flex-column">
        <!-- Formulário para edição -->
        <form asp-controller="EstadoCampo" asp-action="Editar" method="post" class="needs-validation" novalidate>
            <input type="hidden" asp-for="Id">
            <div class="bg-primary text-center text-white p-1" style="font-size:0.8rem; font-weight:600;"><a>-- EDITAR --</a></div>
            <div id="formEditar" class="row">
                <div>
                    <!-- Alert para tratamento de exceções -->
                    @if (TempData["Sucesso"] != null)
                    {
                        <div id="alertForm" class="alert alert-success" role="alert">
                            <button type="button" class="close-alert text-success" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <a>@TempData["Sucesso"]</a>
                        </div>
                    }
                    @if (TempData["Falha"] != null)
                    {
                        <div id="alertForm" class="alert alert-danger" role="alert">
                            <button type="button" class="close-alert text-danger" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <a>@TempData["Falha"]</a>
                        </div>
                    }
                    <!-- End  Alert-->
                </div>
                <div class="form-group col">
                    <label>Estado Campo:</label>
                    <input type="text" asp-for="Nome" class="form-control" maxlength="50" required>
                    <div class="invalid-feedback">Campo Obrigatório.</div>
                </div>
                <div class="modal-footer p-0 m-0 mt-4">
                    <button type="submit" class="btn btn-primary mt-4 ms-2">Editar</button>
                    <a role="button" asp-action="Index" asp-controller="EstadoCampo" id="btnRoles" class="btn btn-secondary mt-4 me-2">Voltar</a>
                </div>
            </div>
        </form>
        <!-- End Formulário-->
    </div>
</div>

ControleGestaoFtth/Views/EstadoCampo/Index.cshtml
@using X.PagedList.Mvc.Core
@model X.PagedList.PagedList<EstadoCampo>
@{

    ViewData["Title"] = "Estado Campo";

}

<!-- Alert para tratamento de exceções -->
@if (TempData["Sucesso"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="close-alert text-success" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <a>@TempData["Sucesso"]</a>
    </div>
}
@if (TempData["Falha"] != null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="close-alert text-danger" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <a>@TempData["Falha"]</a>
    </div>
}
<!-- End  Alert-->
<!-- Menu button vertical -->
<div id="menuBarVertical">
    <a role="button" asp-controller="EstadoCampo" asp-action="Inserir" id="btnRoles" class="btn btn-primary btn-sm" style="padding-top:0.4rem;">Adicionar</a>
</div>
<!-- End -->
<!-- Menu dropdown -->
<div class="container-filter-sm">

    <div class="form-group">
        <label>Estado Campo</label>
        @Html.DropDownList("selectCampo", new SelectList(ViewBag.selectCampo,"Nome","Nome"), "--Todos--",new { @id="dropCampo", @class="custom-select"})
    </div>

</div>
<!-- End -->
<!-- Display partial view base ftth  -->
<div id="ftthLista">
    <div class="d-flex justify-content-center">
        <div class="spinner-border text-secondary m-5" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
</div>
<!-- End Display -->
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <a class="modal-title" id="exampleModalLabel">-- Descrição --</a>
            </div>
            <div class="modal-body">

                <!--Conteudo Display-->
                <div class="d-flex justify-content-center">
                    <div class="spinner-border text-secondary m-5" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                </div>
                <!-- End -->

            </div>
        </div>
    </div>
</div>
<!-- End Modal -->
@section Scripts
    {
    <script>
        //FUNÇÃO REPONSÁVEL PELAS ACÕES JS/JQUERY DA VIEW INDEX CONSTRUTORA
        function EstadoCampoIndex() {

            //VARIAVEIS GLOBAIS LOCAL
            var campo = "";

            //FUNÇÃO DE ATUALIZAÇÃO DISPLAY PARTIALVIEW
            const ftth = (url) => $.get(url,
                {}, function (resposta) {
                    $('#ftthLista').html($(resposta).html());
                    return false;
                });

            //SPINNER LOADER
            const spinnerFtth = (display) => {
                $(display).html(`
                                                <div class= "d-flex justify-content-center">
                                                    <div class="spinner-border text-secondary m-5" role="status">
                                                        <span class="sr-only">Loading...</span>
                                                    </div>
                                                </div>
                                            `   )
            }

            // ATUALIZAR DISPLAY PARTIAL VIEW
            ftth('EstadoCampo/listar');

            //FILTRO DROPDOWNLIST ESTACAO
            $('#dropCampo').on('change', function () {
                //CARREGAR SPINNER LOADER
                spinnerFtth('#ftthLista');

                //CARREGAR VALOR DROPDOWN NA VARIAVEL
                campo = $('#dropCampo').val();

                //CARREGAR TABELA GRID
                ftth('EstadoCampo/listar?nome=' + campo);
                return false;
            });

            //PAGINAÇÃO DA TABELA GRID
            $('#ftthLista, #paged').on('click', '.btnPaged', function () {
                //CARREGAR SPINNER LOADER
                spinnerFtth('#ftthLista');

                //ARMAZENAR HREF EM EXECUÇÃO
                let urlFtth = $(this).find('a').attr('href');

                //CARREGAR GRID VIEW COM OS FILTROS DA BASE FTTH
                ftth(urlFtth + '&nome=' + campo);
                return false;
            });

            //PEGAR VALORES DA TABELA PARA REQUISIÇÃO ATUALIZAR
            $('#ftthLista').on('click', '.tableFtth', function () {

                //VARIAVEL PEGA ID DE REGISTRO DA GRID VIEW
                carregarId = $(this).attr("data-id");

                //CARREGAR DETAHLE VIEW E CHAMAR O COLLAPSE MODAL
                $.get('EstadoCampo/Detalhe?id=' + carregarId,
                    {}, function (resposta) {
                        //CARREGAR SPINNER LOADER
                        spinnerFtth('modal-body');

                        //CARREGAR PARTIAL VIEW
                        $('.modal-body').html($(resposta).find('#displayDetalheFtth').html());
                        return false;
                    });

                //CARREGAR ATRIBUTOS MODAL
                $(this).find('#exampleModal').modal({
                    keyboard: true,
                    backdrop: "static",
                    show: false,

                });
            });

            //CARREGAR VALORES A SEREM EDITADOS NA PAGINA EDITAR
            $('.modal-content').on('click', '#editarFtth', function () {
                window.location.href = 'EstadoCampo/Editar?id=' + carregarId;
            })

        } (EstadoCampoIndex());
    </script>
        }

ControleGestaoFtth/Views/EstadoCampo/Inserir.cshtml
@model EstadoCampo

<div id="formInsert" class="d-flex flex-row justify-content-center">
    <div class="d-flex flex-column">
        <!-- Formulário para edição -->
        <form asp-controller="EstadoCampo" asp-action="Inserir" method="post" class="needs-validation" novalidate>
            <div class="bg-primary text-center text-white p-1" style="font-size:0.8rem; font-weight:600;"><a>-- INSERIR --</a></div>
            <div id="formEditar" name="estadoCampo" class="row">
                <div>
                    <!-- Alert para tratamento de exceções -->
                    @if (TempData["Sucesso"] != null)
                    {
                        <div id="alertForm" class="alert alert-success" role="alert">
                            <button type="button" class="close-alert text-success" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <a>@TempData["Sucesso"]</a>
                        </div>
                    }
                    @if (TempData["Falha"] != null)
                    {
                        <div id="alertForm" class="alert alert-danger" role="alert">
                            <button type="button" class="close-alert text-danger" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <a>@TempData["Falha"]</a>
                        </div>
                    }
                    <!-- End  Alert-->
                </div>
                <div class="form-group col">
                    <label>Estado Campo:</label>
                    <input type="text" asp-for="Nome" class="form-control" maxlength="50" required>
                    <div class="invalid-feedback">Campo Obrigatório.</div>
                </div>
                <div class="modal-footer p-0 m-0 mt-4">
                    <button type="submit" class="btn btn-primary mt-4 ms-2">Inserir</button>
                    <a role="button" asp-action="Index" asp-controller="EstadoCampo" id="btnRoles" class="btn btn-secondary mt-4 me-2">Voltar</a>
                </div>
            </div>
        </form>
        <!-- End Formulário-->
    </div>
</div>

ControleGestaoFtth/Views/EstadoCampo/Listar.cshtml
@using X.PagedList.Mvc.Core
@model X.PagedList.PagedList<EstadoCampo>

<div id="tableUpdate">

    <table class="table">

        <tbody>
            <!-- Condição Nula do Modal -->
            @if (Model != null && Model.Any())
            {
                <!-- Interar valores e preencher grid -->
                foreach (var estadoCampo in Model)
                {

                    <tr id="effectTableFtth">
                        <td>
                            <table class="tableFtth" data-bs-toggle="modal" data-id="@estadoCampo.Id" data-bs-target="#exampleModal" style="cursor: pointer;">
                                <tr>
                                    <td id="rowTitle">
                                        <a>Estado Campo: @estadoCampo.Nome</a>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                }
                <!-- End Interar -->
            }
            else
            {
                <tr>
                    <td>Nenhum resultado.</td>
                </tr>
            }
            <!-- End Condição -->
        </tbody>
    </table>

    <!-- Condição nula do modal e preencher paginação acaso haja (0 > 1) paginas - Construtora -->
    @if (Model != null && Model.Any() && Model.PageCount > 1)
    {
        <div id="paged" class="d-flex justify-content-center">
            <!-- Exibir paginação -->
        @Html.PagedListPager(
        Model, pagina => Url.Action(null , new {pagina}),
        new X.PagedList.Web.Common.PagedListRenderOptions(){
        LiElementClasses = new List<string>{"btn btn-outline-secondary btn-sm btnPaged"}
        })
            <!-- End paginação -->
        </div>
    }
    <!-- End Condição -->
</div>