ControleGestaoFtth/Models/Netwin.cs
using System.ComponentModel.DataAnnotations;

namespace ControleGestaoFtth.Models
{
    public class Netwin
    {
        [Key]
        public int Id { get; set; }
        public int? Codigo { get; set; }
        public string? Tipo { get; set; }
        public string Descricao { get; set; } = null!;
    }
}

ControleGestaoFtth/Controllers/NetwinController.cs
using ControleGestaoFtth.Models;
using ControleGestaoFtth.Repository.Interface;
using Microsoft.AspNetCore.Mvc;

namespace ControleGestaoFtth.Controllers
{
    public class NetwinController : Controller
    {
        private readonly INetwinRepository _netwinRepository;

        public NetwinController(INetwinRepository netwinRepository)
        {
            _netwinRepository = netwinRepository;
        }
        public IActionResult Index()
        {
            ViewData["selectNetwin"] = _netwinRepository.Descricao();
            return View();
        }
        public IActionResult Inserir()
        {
            return View();
        }
        public IActionResult Editar(int id)
        {
            Netwin netwin = _netwinRepository.CarregarId(id);

            return View(netwin);
        }
        public IActionResult Confirmacao(int id)
        {
            Netwin netwin = _netwinRepository.CarregarId(id);

            return View(netwin);
        }

        [HttpPost]
        public IActionResult Inserir(Netwin netwin)
        {
            try
            {
                if (_netwinRepository.NetwinExiste(netwin.Codigo, netwin.Tipo, netwin.Descricao))
                {
                    TempData["Falha"] = $"O Formulário possuí valores existes no banco de dados e não podem ser repetidos, Verificar: Codigo = {netwin.Codigo}, Tipo = {netwin.Tipo} e Descrição = {netwin.Descricao}";

                    return View(netwin);
                }
                else
                {
                    _netwinRepository.Cadastrar(netwin);
                    TempData["Sucesso"] = "Inserido com sucesso.";
                    return RedirectToAction("Inserir");
                }
            }
            catch (Exception error)
            {
                TempData["Falha"] = $"Erro ao inserir - {error}.";
                return View(netwin);
            }
        }
        [HttpPost]
        public IActionResult Editar(Netwin netwin)
        {
            try
            {
                 _netwinRepository.Atualizar(netwin);
                 TempData["Sucesso"] = "Editado com sucesso.";
                 return RedirectToAction("Editar", new { id = netwin.Id });
              
            }
            catch (Exception error)
            {
                TempData["Falha"] = $"Erro ao editar - {error.Message}.";

                return View(netwin);
            }
        }

        [HttpGet]
        public IActionResult Apagar(int id)
        {
            try
            {
                if (!_netwinRepository.UniqueFk().Any(p => p.NetwinId.Equals(id)))
                {
                    _netwinRepository.Deletar(id);
                    TempData["Sucesso"] = $"Excluído com sucesso.";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Falha"] = $"Codigo referente a id N°{id} contém registros relacionais e não pode ser excluída.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception error)
            {
                TempData["Falha"] = $"Erro ao excluir - {error.Message}.";
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public IActionResult Detalhe(int id)
        {
            try
            {
                Netwin netwin = _netwinRepository.CarregarId(id);
                return View(netwin);
            }
            catch (Exception error)
            {
                TempData["Falha"] = $"Erro - {error.Message}.";
                return RedirectToAction("Index");
            }

        }

        [HttpGet]
        public IActionResult Listar(int? pagina, string descricao)
        {
            try
            {
                IEnumerable<Netwin> listar = _netwinRepository.Listar(pagina, descricao);

                return PartialView(listar);
            }
            catch (Exception error)
            {
                TempData["Falha"] = $"Erro - {error.Message}.";
                return PartialView();
            }


        }
    }
}

ControleGestaoFtth/Views/Netwin/Confirmacao.cshtml
@model Netwin
@{
    ViewData["Title"] = "Confirmação";
}
<div class="d-flex flex-row justify-content-center">
    <div class="modal-content">
        <div class="modal-header bg-primary p-2 position-relative">
            <i style="font-size:1.5rem;" class="fa fa-exclamation-circle position-absolute start-0 ms-2 text-white aria-hidden=" true""></i>
            <a style="font-size:0.9rem; font-weight: 600;" class="text-white text-decoration-none">
                -- ATENÇÃO --
            </a>
        </div>
        <div class="modal-body">
            <a id="AvisoConfirmacao">O registro N°@Model.Id referente ao codigo de viabilidade "@Model.Codigo" será excluído permanentemente. <br /><br /> Deseja realmente excluir?   </a>
            <div class="modal-footer mt-4">
                <button onclick="location.href='@Url.Action("Apagar", "Netwin", new {id = Model.Id})'" class="btn btn-primary mt-2">Confirmar</button>
                <button onclick="location.href='@Url.Action("Index", "Netwin")'" class="btn btn-secondary mt-2 cancelar">Cancelar</button>
            </div>
        </div>
    </div>
</div>

ControleGestaoFtth/Views/Netwin/Detalhe.cshtml
@model Netwin

<div id="displayDetalheFtth">
    <!-- Condição Nula do Modal -->
    @if (Model != null)
    {
        <table id="ftthDetalhe">
            <tr>
                <td colspan="2">Codigo: <a>@Model.Codigo</a></td>
            </tr>
            <tr>
                <td>Estação: <a>@Model.Tipo</a></td>
                <td>Sigla: <a>@Model.Descricao</a></td>
            </tr>
        </table>

        <div class="modal-footer mt-4">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
            <a role="button" id="btnRoles" asp-controller="Netwin" asp-action="Editar" asp-route-id="@Model.Id" class="btn btn-primary">Editar</a>
            <a role="button" id="btnRoles" asp-controller="Netwin" asp-action="Confirmacao" asp-route-id="@Model.Id" class="btn btn-danger">Excluir</a>
        </div>
    }
    <!-- End condição -->
</div>

ControleGestaoFtth/Views/Netwin/Editar.cshtml
@model Netwin

<div class="d-flex flex-row justify-content-center">
    <div class="d-flex flex-column">
        <!-- Formulário para edição -->
        <form asp-controller="Netwin" asp-action="Editar" method="post" class="needs-validation" novalidate>
            <input type="hidden" asp-for="Id">
            <div class="bg-primary text-center text-white p-1" style="font-size:0.8rem; font-weight:600;"><a>-- EDITAR --</a></div>
            <div id="formEditar" class="row">
                <div>
                    <!-- Alert para tratamento de exceções -->
                    @if (TempData["Sucesso"] != null)
                    {
                        <div id="alertForm" class="alert alert-success" role="alert">
                            <button type="button" class="close-alert text-success" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <a>@TempData["Sucesso"]</a>
                        </div>
                    }
                    @if (TempData["Falha"] != null)
                    {
                        <div id="alertForm" class="alert alert-danger" role="alert">
                            <button type="button" class="close-alert text-danger" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <a>@TempData["Falha"]</a>
                        </div>
                    }
                    <!-- End  Alert-->
                </div>
                <div class="form-group col">
                    <label>Codigo:</label>
                    <input type="text" asp-for="Codigo" class="form-control" maxlength="50" required>
                    <div class="invalid-feedback">Campo Obrigatório.</div>
                </div>
                <div class="w-100"></div>
                <div class="form-group position-relative col">
                    <label>Tipo:</label>
                    <input type="text" asp-for="Tipo" class="form-control" maxlength="50" required>
                    <div class="invalid-feedback">Campo Obrigatório.</div>
                </div>
                <div class="form-group col">
                    <label>Descrição:</label>
                    <input type="text" asp-for="Descricao" class="form-control" maxlength="50" required>
                    <div class="invalid-feedback">Campo Obrigatório.</div>
                </div>
                <div class="modal-footer p-0 m-0 mt-4">
                    <button type="submit" class="btn btn-primary mt-4 ms-2">Editar</button>
                    <a role="button" asp-action="Index" asp-controller="Netwin" id="btnRoles" class="btn btn-secondary mt-4 me-2">Voltar</a>
                </div>
            </div>
        </form>
        <!-- End Formulário-->
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary p-2 position-relative">
            </div>
            <div class="modal-body">

                <!--Conteudo Display-->
                <div class="d-flex justify-content-center">
                    <div class="spinner-border text-secondary m-5" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                </div>
                <!-- End -->

            </div>
        </div>
    </div>
</div>
<!-- End Modal -->

ControleGestaoFtth/Views/Netwin/Index.cshtml
@using X.PagedList.Mvc.Core
@model X.PagedList.PagedList<Netwin>
@{

    ViewData["Title"] = "Netwin";

}

<!-- Alert para tratamento de exceções -->
@if (TempData["Sucesso"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="close-alert text-success" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <a>@TempData["Sucesso"]</a>
    </div>
}
@if (TempData["Falha"] != null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="close-alert text-danger" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <a>@TempData["Falha"]</a>
    </div>
}
<!-- End  Alert-->
<!-- Menu button vertical -->
<div id="menuBarVertical">
    <a role="button" asp-controller="Netwin" asp-action="Inserir" id="btnRoles" class="btn btn-primary btn-sm" style="padding-top:0.4rem;">Adicionar</a>
</div>
<!-- End -->
<!-- Menu dropdown -->
<div class="container-filter-sm">

    <div class="form-group">
        <label>Viabilidade</label>
        @Html.DropDownList("selectNetwin",new SelectList(ViewBag.selectNetwin,"Descricao","Descricao"), "--Todos--",new { @id="dropNetwin", @class="custom-select"})
    </div>

</div>
<!-- End -->
<!-- Display partial view base ftth  -->
<div id="ftthLista">
    <div class="d-flex justify-content-center">
        <div class="spinner-border text-secondary m-5" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
</div>
<!-- End Display -->
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <a class="modal-title" id="exampleModalLabel">-- Descrição --</a>
            </div>
            <div class="modal-body">

                <!--Conteudo Display-->
                <div class="d-flex justify-content-center">
                    <div class="spinner-border text-secondary m-5" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                </div>
                <!-- End -->

            </div>
        </div>
    </div>
</div>
<!-- End Modal -->
@section Scripts
    {
    <script>
        //FUNÇÃO REPONSÁVEL PELAS ACÕES JS/JQUERY DA VIEW INDEX CONSTRUTORA
        function NetwinIndex() {

            //VARIAVEIS GLOBAIS LOCAL
            var descricao = "";

            //FUNÇÃO DE ATUALIZAÇÃO DISPLAY PARTIALVIEW
            const ftth = (url) => $.get(url,
                {}, function (resposta) {
                    $('#ftthLista').html($(resposta).html());
                    return false;
                });

            //SPINNER LOADER
            const spinnerFtth = (display) => {
                $(display).html(`
                                        <div class= "d-flex justify-content-center">
                                            <div class="spinner-border text-secondary m-5" role="status">
                                                <span class="sr-only">Loading...</span>
                                            </div>
                                        </div>
                                    `   )
            }

            // ATUALIZAR DISPLAY PARTIAL VIEW
            ftth('Netwin/listar');

            //FILTRO DROPDOWNLIST ESTACAO
            $('#dropNetwin').on('change', function () {
                //CARREGAR SPINNER LOADER
                spinnerFtth('#ftthLista');

                //CARREGAR VALOR DROPDOWN NA VARIAVEL
                descricao = $('#dropNetwin').val();

                //CARREGAR TABELA GRID
                ftth('Netwin/listar?descricao=' + descricao);
                return false;
            });

            //PAGINAÇÃO DA TABELA GRID
            $('#ftthLista, #paged').on('click', '.btnPaged', function () {
                //CARREGAR SPINNER LOADER
                spinnerFtth('#ftthLista');

                //ARMAZENAR HREF EM EXECUÇÃO
                let urlFtth = $(this).find('a').attr('href');

                //CARREGAR GRID VIEW COM OS FILTROS DA BASE FTTH
                ftth(urlFtth + '&descricao=' + descricao)
                return false;
            });

            //PEGAR VALORES DA TABELA PARA REQUISIÇÃO ATUALIZAR
            $('#ftthLista').on('click', '.tableFtth', function () {

                //VARIAVEL PEGA ID DE REGISTRO DA GRID VIEW
                carregarId = $(this).attr("data-id");

                //CARREGAR DETAHLE VIEW E CHAMAR O COLLAPSE MODAL
                $.get('Netwin/Detalhe?id=' + carregarId,
                    {}, function (resposta) {
                        //CARREGAR SPINNER LOADER
                        spinnerFtth('modal-body');

                        //CARREGAR PARTIAL VIEW
                        $('.modal-body').html($(resposta).find('#displayDetalheFtth').html());
                        return false;
                    });

                //CARREGAR ATRIBUTOS MODAL
                $(this).find('#exampleModal').modal({
                    keyboard: true,
                    backdrop: "static",
                    show: false,

                });
            });

            //CARREGAR VALORES A SEREM EDITADOS NA PAGINA EDITAR
            $('.modal-content').on('click', '#editarFtth', function () {
                window.location.href = 'Estacao/Editar?id=' + carregarId;
            })

        } (NetwinIndex());
    </script>
        }

ControleGestaoFtth/Views/Netwin/Inserir.cshtml
@model Netwin

<div id="formInsert" class="d-flex flex-row justify-content-center">
    <div class="d-flex flex-column">
        <!-- Formulário para edição -->
        <form asp-controller="Netwin" asp-action="Inserir" method="post" class="needs-validation" novalidate>
            <div class="bg-primary text-center text-white p-1" style="font-size:0.8rem; font-weight:600;"><a>-- INSERIR --</a></div>
            <div id="formEditar" name="viabilidade" class="row">
                <div>
                    <!-- Alert para tratamento de exceções -->
                    @if (TempData["Sucesso"] != null)
                    {
                        <div id="alertForm" class="alert alert-success" role="alert">
                            <button type="button" class="close-alert text-success" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <a>@TempData["Sucesso"]</a>
                        </div>
                    }
                    @if (TempData["Falha"] != null)
                    {
                        <div id="alertForm" class="alert alert-danger" role="alert">
                            <button type="button" class="close-alert text-danger" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <a>@TempData["Falha"]</a>
                        </div>
                    }
                    <!-- End  Alert-->
                </div>
                <div class="form-group col">
                    <label>Codigo:</label>
                    <input type="number" asp-for="Codigo" class="form-control" min="0" max="1000" required>
                    <div class="invalid-feedback">Campo Obrigatório.</div>
                </div>
                <div class="w-100"></div>
                <div class="form-group position-relative col">
                    <label>Tipo:</label>
                    <input type="text" asp-for="Tipo" class="form-control" maxlength="50" required>
                    <div class="invalid-feedback">Campo Obrigatório.</div>
                </div>
                <div class="form-group col">
                    <label>Descrição:</label>
                    <input type="text" asp-for="Descricao" class="form-control" maxlength="50" required>
                    <div class="invalid-feedback">Campo Obrigatório.</div>
                </div>
                <div class="modal-footer p-0 m-0 mt-4">
                    <button type="submit" class="btn btn-primary mt-4 ms-2">Inserir</button>
                    <a role="button" asp-action="Index" asp-controller="Netwin" id="btnRoles" class="btn btn-secondary mt-4 me-2">Voltar</a>
                </div>
            </div>
        </form>
        <!-- End Formulário-->
    </div>
</div>

ControleGestaoFtth/Views/Netwin/Listar.cshtml
@using X.PagedList.Mvc.Core
@model X.PagedList.PagedList<Netwin>

<div id="tableUpdate">

    <table class="table">

        <tbody>
            <!-- Condição Nula do Modal -->
            @if (Model != null && Model.Any())
            {
                <!-- Interar valores e preencher grid -->
                foreach (var netwin in Model)
                {

                    <tr id="effectTableFtth">
                        <td>
                            <table class="tableFtth" data-bs-toggle="modal" data-id="@netwin.Id" data-bs-target="#exampleModal" style="cursor: pointer;">
                                <tr>
                                    <td width="25%" id="rowTitle">
                                        <a>Codigo: @netwin.Codigo</a>
                                    </td>
                                    <td width="30%">
                                        <a>Tipo: @netwin.Tipo</a>
                                    </td>
                                    <td width="45%">
                                        <a>Descrição: @netwin.Descricao</a>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                }
                <!-- End Interar -->
            }
            else
            {
                <tr>
                    <td>Nenhum resultado.</td>
                </tr>
            }
            <!-- End Condição -->
        </tbody>
    </table>

    <!-- Condição nula do modal e preencher paginação acaso haja (0 > 1) paginas - Construtora -->
    @if (Model != null && Model.Any() && Model.PageCount > 1)
    {
        <div id="paged" class="d-flex justify-content-center">
            <!-- Exibir paginação -->
        @Html.PagedListPager(
        Model, pagina => Url.Action(null , new {pagina}),
        new X.PagedList.Web.Common.PagedListRenderOptions(){
        LiElementClasses = new List<string>{"btn btn-outline-secondary btn-sm btnPaged"}
        })
            <!-- End paginação -->
        </div>
    }
    <!-- End Condição -->
</div>