ControleGestaoFtth/Models/Construtora.cs
using System.ComponentModel.DataAnnotations;

namespace ControleGestaoFtth.Models
{
    public class Construtora
    {
        [Key]
        public int Id { get; set; }
        public string Nome { get; set; } = null!;
    }
}

ControleGestaoFtth/Models/Construtoras.cs
using System.ComponentModel.DataAnnotations;

namespace ControleGestaoFtth.Models
{
    public class Construtoras
    {
        [Key]
        public int Id { get; set; }
        public string? CHAVE { get; set; }
        public int? EstacoesId { get; set; }
        public int? TipoObraId { get; set; }
        public string? CDO { get; set; }
        public int? Cabo { get; set; }
        public int? Celula { get; set; }
        public int? Capacidade { get; set; }
        public int? TotalUms { get; set; }
        public string? Endereco { get; set; }
        public int? EstadoCamposId { get; set; }
        public int? StatesId { get; set; }
        public DateTime? AceitacaoData { get; set; }
        public string? AceitacaoMesRef { get; set; }
        public string? Observacao { get; set; }
        public int? Viabilidade { get; set; }
        public string? Meta { get; set; }
        public DateTime? DatadeConstrucao { get; set; }
        public string? EquipedeConstrucao { get; set; }
        public DateTime? DatadoTeste { get; set; }
        public string? Tecnico { get; set; }
        public DateTime? DatadeRecebimento { get; set; }
        public int? BobinaLancamento { get; set; }
        public int? BobinaRecepcao { get; set; }
        public int? QuantidadeDeTeste { get; set; }
        public string? PosicaoICX_DGO  { get; set; }
        public int? SplitterCEOS { get; set; }
        public int? FibraDGO { get; set; }
    }
}

ControleGestaoFtth/Controllers/ConstrutoraController.cs
using ControleGestaoFtth.Models;
using ControleGestaoFtth.Repository;
using ControleGestaoFtth.Repository.Interface;
using Microsoft.AspNetCore.Mvc;

namespace ControleGestaoFtth.Controllers
{
    public class ConstrutoraController : Controller
    {
        private readonly IConstrutoraRepository _construtoraRepository;

        public ConstrutoraController(IConstrutoraRepository construtoraRepository)
        {
            _construtoraRepository = construtoraRepository;
        }
        public IActionResult Index()
        {
            ViewData["selectConstrutora"] = _construtoraRepository.Obras();
            return View();
        }
        public IActionResult Inserir()
        {
            return View();
        }
        public IActionResult Editar(int id)
        {
            Construtora Construtora = _construtoraRepository.CarregarId(id);

            return View(Construtora);
        }
        public IActionResult Confirmacao(int id)
        {
            Construtora Construtora = _construtoraRepository.CarregarId(id);

            return View(Construtora);
        }

        [HttpPost]
        public IActionResult Inserir(Construtora Construtora)
        {
            try
            {
                if (_construtoraRepository.ContrutoraExiste(Construtora.Nome))
                {
                    TempData["Falha"] = $"Tipo obra {Construtora.Nome} já existe.";

                    return View(Construtora);
                }
                else
                {
                    _construtoraRepository.Cadastrar(Construtora);
                    TempData["Sucesso"] = "Inserido com sucesso.";
                    return RedirectToAction("Inserir");
                }
            }
            catch (Exception error)
            {
                TempData["Falha"] = $"Erro ao inserir - {error}.";
                return View(Construtora);
            }
        }
        [HttpPost]
        public IActionResult Editar(Construtora Construtora)
        {
            try
            {
                _construtoraRepository.Atualizar(Construtora);
                TempData["Sucesso"] = "Editado com sucesso.";
                return RedirectToAction("Editar", new { id = Construtora.Id });
            }
            catch (Exception error)
            {
                TempData["Falha"] = $"Erro ao editar - {error.Message}.";

                return View(Construtora);
            }
        }

        [HttpGet]
        public IActionResult Apagar(int id)
        {
            try
            {
                if (!_construtoraRepository.UniqueFk().Any(p => p.ConstrutorasId.Equals(id)))
                {
                    _construtoraRepository.Deletar(id);
                    TempData["Sucesso"] = $"Excluído com sucesso.";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Falha"] = $"Construtora N°{id} contém registros relacionais e não pode ser excluída.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception error)
            {
                TempData["Falha"] = $"Erro ao excluir - {error.Message}.";
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public IActionResult Detalhe(int id)
        {
            try
            {
                Construtora Construtora = _construtoraRepository.CarregarId(id);

                return View(Construtora);
            }
            catch (Exception error)
            {
                TempData["Falha"] = $"Erro - {error.Message}.";
                return RedirectToAction("Index");
            }

        }

        [HttpGet]
        public IActionResult Listar(int? pagina, string nome)
        {
            try
            {
                IEnumerable<Construtora> listar = _construtoraRepository.Listar(pagina, nome);

                return PartialView(listar);
            }
            catch (Exception error)
            {
                TempData["Falha"] = $"Erro - {error.Message}.";
                return PartialView();
            }


        }
    }
}

ControleGestaoFtth/Views/Construtora/Confirmacao.cshtml
@model Construtora
@{
    ViewData["Title"] = "Confirmação";
}
<div class="d-flex flex-row justify-content-center">
    <div class="modal-content">
        <div class="modal-header bg-primary p-2 position-relative">
            <i style="font-size:1.5rem;" class="fa fa-exclamation-circle position-absolute start-0 ms-2 text-white aria-hidden=" true""></i>
            <a style="font-size:0.9rem; font-weight: 600;" class="text-white text-decoration-none">
                -- ATENÇÃO --
            </a>
        </div>
        <div class="modal-body">
            <a id="AvisoConfirmacao">O registro N°@Model.Id referente a "@Model.Nome" será excluído permanentemente. <br /><br /> Deseja realmente excluir?   </a>
            <div class="modal-footer mt-4">
                <button onclick="location.href='@Url.Action("Apagar", "Construtora", new {id = Model.Id})'" class="btn btn-primary mt-2">Confirmar</button>
                <button onclick="location.href='@Url.Action("Index", "Construtora")'" class="btn btn-secondary mt-2 cancelar">Cancelar</button>
            </div>
        </div>
    </div>
</div>

ControleGestaoFtth/Views/Construtora/Detalhe.cshtml
@model Construtora

<div id="displayDetalheFtth">
    <!-- Condição Nula do Modal -->
    @if (Model != null)
    {
        <table id="ftthDetalhe">
            <tr>
                <td colspan="2">Tipo de Obra: <a>@Model.Nome</a></td>
            </tr>
        </table>

        <div class="modal-footer mt-4">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
            <a role="button" id="btnRoles" asp-controller="Construtora" asp-action="Editar" asp-route-id="@Model.Id" class="btn btn-primary">Editar</a>
            <a role="button" id="btnRoles" asp-controller="Construtora" asp-action="Confirmacao" asp-route-id="@Model.Id" class="btn btn-danger">Excluir</a>
        </div>
    }
    <!-- End condição -->
</div>

ControleGestaoFtth/Views/Construtora/Editar.cshtml
@model Construtora

<div class="d-flex flex-row justify-content-center">
    <div class="d-flex flex-column">
        <!-- Formulário para edição -->
        <form asp-controller="Construtora" asp-action="Editar" method="post" class="needs-validation" novalidate>
            <input type="hidden" asp-for="Id">
            <div class="bg-primary text-center text-white p-1" style="font-size:0.8rem; font-weight:600;"><a>-- EDITAR --</a></div>
            <div id="formEditar" class="row">
                <div>
                    <!-- Alert para tratamento de exceções -->
                    @if (TempData["Sucesso"] != null)
                    {
                        <div id="alertForm" class="alert alert-success" role="alert">
                            <button type="button" class="close-alert text-success" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <a>@TempData["Sucesso"]</a>
                        </div>
                    }
                    @if (TempData["Falha"] != null)
                    {
                        <div id="alertForm" class="alert alert-danger" role="alert">
                            <button type="button" class="close-alert text-danger" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <a>@TempData["Falha"]</a>
                        </div>
                    }
                    <!-- End  Alert-->
                </div>
                <div class="form-group col">
                    <label>Tipo Obra:</label>
                    <input type="text" asp-for="Nome" class="form-control" maxlength="50" required>
                    <div class="invalid-feedback">Campo Obrigatório.</div>
                </div>
                <div class="modal-footer p-0 m-0 mt-4">
                    <button type="submit" class="btn btn-primary mt-4 ms-2">Editar</button>
                    <a role="button" asp-action="Index" asp-controller="Construtora" id="btnRoles" class="btn btn-secondary mt-4 me-2">Voltar</a>
                </div>
            </div>
        </form>
        <!-- End Formulário-->
    </div>
</div>

ControleGestaoFtth/Views/Construtora/Index.cshtml
@using X.PagedList.Mvc.Core
@model X.PagedList.PagedList<Construtora>
@{

    ViewData["Title"] = "Construtora";

}

<!-- Alert para tratamento de exceções -->
@if (TempData["Sucesso"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="close-alert text-success" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <a>@TempData["Sucesso"]</a>
    </div>
}
@if (TempData["Falha"] != null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="close-alert text-danger" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <a>@TempData["Falha"]</a>
    </div>
}
<!-- End  Alert-->
<!-- Menu button vertical -->
<div id="menuBarVertical">
    <a role="button" asp-controller="Construtora" asp-action="Inserir" id="btnRoles" class="btn btn-primary btn-sm" style="padding-top:0.4rem;">Adicionar</a>
</div>
<!-- End -->
<!-- Menu dropdown -->
<div class="container-filter-sm">

    <div class="form-group">
        <label>Construtora</label>
        @Html.DropDownList("selectConstrutora", new SelectList(ViewBag.selectConstrutora,"Nome","Nome"), "--Todos--",new { @id="dropConstrutora", @class="custom-select"})
    </div>

</div>
<!-- End -->
<!-- Display partial view base ftth  -->
<div id="ftthLista">
    <div class="d-flex justify-content-center">
        <div class="spinner-border text-secondary m-5" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
</div>
<!-- End Display -->
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <a class="modal-title" id="exampleModalLabel">-- Descrição --</a>
            </div>
            <div class="modal-body">

                <!--Conteudo Display-->
                <div class="d-flex justify-content-center">
                    <div class="spinner-border text-secondary m-5" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                </div>
                <!-- End -->

            </div>
        </div>
    </div>
</div>
<!-- End Modal -->
@section Scripts
    {
    <script>
        //FUNÇÃO REPONSÁVEL PELAS ACÕES JS/JQUERY DA VIEW INDEX CONSTRUTORA
        function ConstrutoraIndex() {

            //VARIAVEIS GLOBAIS LOCAL
            var nomeConstrutora = "";

            //FUNÇÃO DE ATUALIZAÇÃO DISPLAY PARTIALVIEW
            const ftth = (url) => $.get(url,
                {}, function (resposta) {
                    $('#ftthLista').html($(resposta).html());
                    return false;
                });

            //SPINNER LOADER
            const spinnerFtth = (display) => {
                $(display).html(`
                                                <div class= "d-flex justify-content-center">
                                                    <div class="spinner-border text-secondary m-5" role="status">
                                                        <span class="sr-only">Loading...</span>
                                                    </div>
                                                </div>
                                            `   )
            }

            // ATUALIZAR DISPLAY PARTIAL VIEW
            ftth('Construtora/listar');

            //FILTRO DROPDOWNLIST ESTACAO
            $('#dropConstrutora').on('change', function () {
                //CARREGAR SPINNER LOADER
                spinnerFtth('#ftthLista');

                //CARREGAR VALOR DROPDOWN NA VARIAVEL
                nomeConstrutora = $('#dropConstrutora').val();

                //CARREGAR TABELA GRID
                ftth('Construtora/listar?nome=' + nomeConstrutora);
                return false;
            });

            //PAGINAÇÃO DA TABELA GRID
            $('#ftthLista, #paged').on('click', '.btnPaged', function () {
                //CARREGAR SPINNER LOADER
                spinnerFtth('#ftthLista');

                //ARMAZENAR HREF EM EXECUÇÃO
                let urlFtth = $(this).find('a').attr('href');

                //CARREGAR GRID VIEW COM OS FILTROS DA BASE FTTH
                ftth(urlFtth + '&nome=' + nomeConstrutora);
                return false;
            });

            //PEGAR VALORES DA TABELA PARA REQUISIÇÃO ATUALIZAR
            $('#ftthLista').on('click', '.tableFtth', function () {

                //VARIAVEL PEGA ID DE REGISTRO DA GRID VIEW
                carregarId = $(this).attr("data-id");

                //CARREGAR DETAHLE VIEW E CHAMAR O COLLAPSE MODAL
                $.get('Construtora/Detalhe?id=' + carregarId,
                    {}, function (resposta) {
                        //CARREGAR SPINNER LOADER
                        spinnerFtth('modal-body');

                        //CARREGAR PARTIAL VIEW
                        $('.modal-body').html($(resposta).find('#displayDetalheFtth').html());
                        return false;
                    });

                //CARREGAR ATRIBUTOS MODAL
                $(this).find('#exampleModal').modal({
                    keyboard: true,
                    backdrop: "static",
                    show: false,

                });
            });

            //CARREGAR VALORES A SEREM EDITADOS NA PAGINA EDITAR
            $('.modal-content').on('click', '#editarFtth', function () {
                window.location.href = 'Construtora/Editar?id=' + carregarId;
            })

        } (ConstrutoraIndex());
    </script>
        }

ControleGestaoFtth/Views/Construtora/Inserir.cshtml
@model Construtora

<div id="formInsert" class="d-flex flex-row justify-content-center">
    <div class="d-flex flex-column">
        <!-- Formulário para edição -->
        <form asp-controller="Construtora" asp-action="Inserir" method="post" class="needs-validation" novalidate>
            <div class="bg-primary text-center text-white p-1" style="font-size:0.8rem; font-weight:600;"><a>-- INSERIR --</a></div>
            <div id="formEditar" name="tipoObra" class="row">
                <div>
                    <!-- Alert para tratamento de exceções -->
                    @if (TempData["Sucesso"] != null)
                    {
                        <div id="alertForm" class="alert alert-success" role="alert">
                            <button type="button" class="close-alert text-success" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <a>@TempData["Sucesso"]</a>
                        </div>
                    }
                    @if (TempData["Falha"] != null)
                    {
                        <div id="alertForm" class="alert alert-danger" role="alert">
                            <button type="button" class="close-alert text-danger" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <a>@TempData["Falha"]</a>
                        </div>
                    }
                    <!-- End  Alert-->
                </div>
                <div class="form-group col">
                    <label>Tipo Obra:</label>
                    <input type="text" asp-for="Nome" class="form-control" maxlength="50" required>
                    <div class="invalid-feedback">Campo Obrigatório.</div>
                </div>
                <div class="modal-footer p-0 m-0 mt-4">
                    <button type="submit" class="btn btn-primary mt-4 ms-2">Inserir</button>
                    <a role="button" asp-action="Index" asp-controller="Construtora" id="btnRoles" class="btn btn-secondary mt-4 me-2">Voltar</a>
                </div>
            </div>
        </form>
        <!-- End Formulário-->
    </div>
</div>

ControleGestaoFtth/Views/Construtora/Lista.cshtml
@using X.PagedList.Mvc.Core
@model X.PagedList.PagedList<Construtora>

<div id="panelUpdate">

     @if (Model != null && Model.Any())
    {

        <div class="form-group" id="plCdo">
            <label>CDO</label>
            @Html.DropDownList("selectCdoFilter", new SelectList(ViewBag.selectCdoFilter,"CDO","CDO"), "--Todos--",new { @id="dropCdo", @class="custom-select"})
        </div>

        <div class="form-group" id="plCabo">
            <label>Cabo</label>
            @Html.DropDownList("selectCaboFilter", new SelectList(ViewBag.selectCaboFilter,"Cabo","Cabo"), "--Todos--",new { @id="dropCabo", @class="custom-select"})
        </div>

        <div class="form-group" id="plCelula">
            <label>Celula</label>
            @Html.DropDownList("selectCelulaFilter", new SelectList(ViewBag.selectCelulaFilter,"Celula","Celula"), "--Todos--",new { @id="dropCelula", @class="custom-select"})
        </div>

        <div id="metricaFtth">
            <a></a>
    </div>
    }

</div>

<div id="tableUpdate">

    <table class="table">

        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (var construtora in Model)
                {
                    <tr id="effectTableFtth">
                        <td>
                            <table class="tableFtth" data-bs-toggle="modal" data-id="@construtora.Id" data-bs-target="#exampleModal" style="cursor: pointer;">
                               <tr>
                                <td id="rowTitle" colspan="1" align="center" style="width: 20%;">
                                    <a>@construtora.Estacao.NomeEstacao</a>
                                </td>
                                    <td width="20%" colspan="2">
                                        <a>Cabo: @construtora.Cabo</a>
                                 </td>
                                <td width="20%" align="center" valign="baseline">
                                        <a>Data Recebimento: @construtora.DatadeRecebimento?.ToString("dd/MM/yyyy")</a>
                                </td>
                                 <td width="20%">
                                        <a>Data Teste: @construtora.DatadoTeste?.ToString("dd/MM/yyyy")</a>
                                    </td>
                                  <td width="20%">
                                        <a>Técnico: @construtora.Tecnico</a>
                                </td>
                                </tr>
                                <tr>
                                <td>
                                        <a>CDO: @construtora.CDO</a>
                                </td>
                                    <td width="5%">
                                        <a>Celula: @construtora.Celula</a>
                                    </td>
                                    <td width="5%">
                                        <a>UMs: @construtora.TotalUms</a>
                                    </td>
                                    <td align="center" valign="baseline"><a>@construtora.Netwin?.Tipo</a></td>
                                <td>
                                        <a>Data Construções: @construtora.DatadeConstrucao?.ToString("dd/MM/yyyy")</a>
                                </td>
                                  <td>
                                        <a>Equipe: @construtora.EquipedeConstrucao</a>
                                </td>
                            </tr>
                            </table>
                         </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td>Nenhum resultado.</td>
                </tr>
            }
        </tbody>
    </table>
   
    @if (Model != null && Model.Any() && Model.PageCount > 1)
        {
        <div id="paged" class="d-flex justify-content-center">
            @Html.PagedListPager(
                Model, pagina => Url.Action(null , new {pagina}),
                new X.PagedList.Web.Common.PagedListRenderOptions(){
                LiElementClasses = new List<string>{"btn btn-outline-secondary btn-sm btnPaged"}
              })
         </div>
         }
</div>

ControleGestaoFtth/Views/Construtora/Listar.cshtml
@using X.PagedList.Mvc.Core
@model X.PagedList.PagedList<Construtora>

<div id="tableUpdate">

    <table class="table">

        <tbody>
            <!-- Condição Nula do Modal -->
            @if (Model != null && Model.Any())
            {
                <!-- Interar valores e preencher grid -->
                foreach (var Construtora in Model)
                {

                    <tr id="effectTableFtth">
                        <td>
                            <table class="tableFtth" data-bs-toggle="modal" data-id="@Construtora.Id" data-bs-target="#exampleModal" style="cursor: pointer;">
                                <tr>
                                    <td id="rowTitle">
                                        <a>Tipo de Obra: @Construtora.Nome</a>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                }
                <!-- End Interar -->
            }
            else
            {
                <tr>
                    <td>Nenhum resultado.</td>
                </tr>
            }
            <!-- End Condição -->
        </tbody>
    </table>

    <!-- Condição nula do modal e preencher paginação acaso haja (0 > 1) paginas - Construtora -->
    @if (Model != null && Model.Any() && Model.PageCount > 1)
    {
        <div id="paged" class="d-flex justify-content-center">
            <!-- Exibir paginação -->
        @Html.PagedListPager(
        Model, pagina => Url.Action(null , new {pagina}),
        new X.PagedList.Web.Common.PagedListRenderOptions(){
        LiElementClasses = new List<string>{"btn btn-outline-secondary btn-sm btnPaged"}
        })
            <!-- End paginação -->
        </div>
    }
    <!-- End Condição -->
</div>

ControleGestaoFtth/Views/Construtora/_Listar.cshtml
@using X.PagedList.Mvc.Core
@model X.PagedList.PagedList<Construtora>

<table class="table">
    <tbody>
        @if (Model != null && Model.Any())
        {
            foreach (var construtora in Model)
            {
                <tr>
                    <th scope="row">@construtora.CHAVE</th>
                    <td>@construtora.Estacao?.Responsavel</td>
                    <td>@construtora.Estacao?.NomeEstacao</td>
                    <td>@construtora.TipoObra?.Nome</td>
                    <td>@construtora.CDO</td>
                </tr>
            }
        }
    </tbody>
</table>