ControleGestaoFtth/Controllers/EnderecoTotaisController.cs
using ControleGestaoFtth.ComponentModel;
using ControleGestaoFtth.Models;
using ControleGestaoFtth.Repository.Interface;
using CsvHelper;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Globalization;

namespace ControleGestaoFtth.Controllers
{
    public class EnderecoTotaisController : Controller
    {
        private readonly IEnderecoTotaisRepository _enderecoTotaisRepository;
        private readonly ProgressBar _progressBar;

        public EnderecoTotaisController(IEnderecoTotaisRepository enderecoTotaisRepository, ProgressBar progressBar)
        {
            _enderecoTotaisRepository = enderecoTotaisRepository;
            _progressBar = progressBar;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Importar()
        {
            return PartialView();
        }
        [HttpPost]
        public async Task<IActionResult> Importar(IFormFile file)
        {
            try
            {
                //if (file != null && file.Length > 0)
                //{
                    // Lê o arquivo CSV
                    var reader = new StreamReader(file.OpenReadStream());
                    var csv = new CsvReader(reader, CultureInfo.InvariantCulture);
                    var records = csv.GetRecords<Enderecostotais>().ToList();
                    int contador = 0;

                    await Task.Run(() =>
                    {
                        // Grava os dados no banco de dados
                        foreach (var enderecostotais in records)
                        {
                            //CARREGAR PROGRESSO
                            _progressBar.Progresso = contador++;

                            var entity = new Enderecostotais
                            {
                                //CARREGAR PROPRIEDADES A SEREM IMPORTADAS
                                //Id = enderecostotais.Id,
                                CELULA = enderecostotais.CELULA,
                                ESTACAO_ABASTECEDORA = enderecostotais.ESTACAO_ABASTECEDORA,
                                UF = enderecostotais.UF,
                                MUNICIPIO = enderecostotais.MUNICIPIO,
                                LOCALIDADE = enderecostotais.LOCALIDADE,
                                COD_LOCALIDADE = enderecostotais.COD_LOCALIDADE,
                                LOCALIDADE_ABREV = enderecostotais.LOCALIDADE_ABREV,
                                LOGRADOURO = enderecostotais.LOGRADOURO,
                                COD_LOGRADOURO = enderecostotais.COD_LOGRADOURO,
                                NUM_FACHADA = enderecostotais.NUM_FACHADA,
                                COMPLEMENTO = enderecostotais.COMPLEMENTO,
                                COMPLEMENTO2 = enderecostotais.COMPLEMENTO2,
                                COMPLEMENTO3 = enderecostotais.COMPLEMENTO3,
                                CEP = enderecostotais.CEP,
                                BAIRRO = enderecostotais.BAIRRO,
                                COD_SURVEY = enderecostotais.COD_SURVEY,
                                QUANTIDADE_UMS = enderecostotais.QUANTIDADE_UMS,
                                COD_VIABILIDADE = enderecostotais.COD_VIABILIDADE,
                                TIPO_VIABILIDADE = enderecostotais.TIPO_VIABILIDADE,
                                TIPO_REDE = enderecostotais.TIPO_REDE,
                                UCS_RESIDENCIAIS = enderecostotais.UCS_RESIDENCIAIS,
                                UCS_COMERCIAIS = enderecostotais.UCS_COMERCIAIS,
                                NOME_CDO = enderecostotais.NOME_CDO,
                                ID_ENDERECO = enderecostotais.ID_ENDERECO,
                                LATITUDE = enderecostotais.LATITUDE,
                                LONGITUDE = enderecostotais.LONGITUDE,
                                TIPO_SURVEY = enderecostotais.TIPO_SURVEY,
                                REDE_INTERNA = enderecostotais.REDE_INTERNA,
                                UMS_CERTIFICADAS = enderecostotais.UMS_CERTIFICADAS,
                                REDE_EDIF_CERT = enderecostotais.REDE_EDIF_CERT,
                                NUM_PISOS = enderecostotais.NUM_PISOS,
                                DISP_COMERCIAL = enderecostotais.DISP_COMERCIAL,
                                ESTADO_CONTROLE = enderecostotais.ESTADO_CONTROLE,
                                DATA_ESTADO_CONTROLE = enderecostotais.DATA_ESTADO_CONTROLE,
                                ID_CELULA = enderecostotais.ID_CELULA,
                                QUANTIDADE_HCS = enderecostotais.QUANTIDADE_HCS,
                                PROJETO = enderecostotais.PROJETO,
                            };

                            //VERIFICA SE O REGISTRO DA CSV EXISTE NO BANCO DE DADOS
                            if (_enderecoTotaisRepository.EnderecoTotaisExiste(entity.ID_ENDERECO))
                            {
                                //SE EXISTIR, ATUALIZAR
                                //_enderecoTotaisRepository.Atualizar(entity);
                                Debug.WriteLine("----------------- ATUALIZAR -----------------");
                            }
                            else
                            {
                                //SE NÃO EXISTIR, CADASTRAR
                                //_enderecoTotaisRepository.Cadastrar(entity);
                                Debug.WriteLine("----------------- CADASTRAR -----------------");
                            }

                        };
                    });

                    //ALETA DE SUCESSO
                    TempData["Sucesso"] = "CSV [Endereço Totais] importado com sucesso.";
                    //RESETAR BARRA DE PROGRESSO SESSÃO IMPORT
                    _progressBar.Progresso = 0;
                    // Redirecionar o usuário de volta para a página inicial
                    return RedirectToAction("Index");

                //}
                /*else
                {
                    //ALERTA DE FALHA
                    TempData["Falha"] = "O Arquivo CSV está vazio.";
                    //RESETAR BARRA DE PROGRESSO SESSÃO IMPORT
                    _progressBar.Progresso = 0;
                    // Redirecionar o usuário de volta para a página inicial
                    return RedirectToAction("Index");
                }*/
            }
            catch (Exception ex)
            {
                //ALERTA DE FALHA
                TempData["Falha"] = $"ATENÇÃO! {ex.Message}";
                //RESETAR BARRA DE PROGRESSO SESSÃO IMPORT

                // Redirecionar o usuário de volta para a página inicial
                return RedirectToAction("Index");
            }
        }
    }
}

ControleGestaoFtth/Views/EnderecoTotais/Importar.cshtml
<form method="post" enctype="multipart/form-data" asp-controller="EnderecoTotais" asp-action="Importar" class="was-validated">
    <div class="d-flex justify-content-between">
        <div class="form-group">
            <input type="file" name="file" id="file" class="form-control-file" required>
        </div>
        <button id="btnUpload" type="submit">Upload</button>
    </div>
</form>

<hr>
<div id="display-view">
</div>

ControleGestaoFtth/Views/EnderecoTotais/Index.cshtml
@using X.PagedList.Mvc.Core
@model X.PagedList.PagedList<Enderecostotais>
@{

    ViewData["Title"] = "Endereços Totais";

}

<!-- Alert para tratamento de exceções -->
@if (TempData["Sucesso"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="close-alert text-success" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <a>@TempData["Sucesso"]</a>
    </div>
}
@if (TempData["Falha"] != null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="close-alert text-danger" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <a>@TempData["Falha"]</a>
    </div>
}
<!-- End  Alert-->
<!-- Menu button vertical -->
<div id="menuBarVertical">
    <button data-bs-toggle="modal" id="baseImport" data-bs-target="#modelImport" class="btn btn-warning btn-sm ms-3 ms-2">Importar CSV</button>
</div>
<!-- End -->
<!-- Modal -->
<div class="modal fade" id="modelImport" tabindex="-1" role="dialog" data-bs-backdrop="static" data-bs-keyboard="false" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="d-flex m-0">
            <div class="modal-content m-0">
                <div class="modal-header m-0 p-0">
                    <a class="modal-title w-100 text-center">-- Importar CSV Endereços Totais --</a>
                    <button type="button" id="close-model" class="close m-0 p-0" data-bs-dismiss="modal" aria-label="Close">x</button>
                </div>
                <div class="modal-body">
                    <!--Conteudo Display-->
                    <!-- End -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Modal -->

@section Scripts
    {
    <script>
        //FUNÇÃO REPONSÁVEL PELAS ACÕES JS/JQUERY DA VIEW INDEX CONSTRUTORA
        function EnderecoTotaisIndex() {
            //SPINNER LOADER
            const spinnerFtth = (display) => {
                $(display).html(`
                                                <div class= "d-flex justify-content-center">
                                                    <div class="spinner-border text-secondary m-5" role="status">
                                                        <span class="sr-only">Loading...</span>
                                                    </div>
                                                </div>
                                            `   )
            }
        //IMPORTAR MODELO BASE
            $('#baseImport').on('click', function () {
                //CARREGAR SPINNER LOADER
                spinnerFtth('.modal-body');
                //CARREGAR MODEL DE IMPORTAÇÃO MODELO BASE
                $.get('EnderecoTotais/Importar',
                    {}, function (resposta) {
                        $('.modal-body').html(resposta);
                        return false;
                    });
                return false;
            });

            //UPLOAD MODELO IMPORTAÇÃO BASE
            $('.modal-body').on('submit', 'form', function () {
                $(this).find("button[type='submit']").prop('disabled', true);
                $('.modal-header #close-model').attr("disabled", "disabled");
                setInterval(function () {
                    $.get('/ProgressBar',
                        {}, function (resposta) {
                            $('.modal-body #display-view').html(resposta);
                             return false;
                        });
                }, 100);
            });

        } (EnderecoTotaisIndex());
    </script>
    }